import Head from 'next/head';
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar/Navbar';
import Header from '@/components/Header/Header';
import AboutUs from '@/components/container/AboutUs/AboutUs';
import CTA from '@/components/CTA/CTA';
import Footer from '@/components/container/Footer/Footer';
import Gallery from '@/components/container/Gallery/Gallery';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar />
        <Header />
        <AboutUs />
        <Gallery />
        <CTA />
        <Footer />
      </div>
    </>
  );
}
